#!/bin/sh

# Copyright (c) 2015 - thewisenerd <thewisenerd@protonmail.com>

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

if ! type python3 > /dev/null; then
  sudo apt-get install -y python3
fi

python3 -c "import tkinter" >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  sudo apt-get install -y python3-tk
fi

python3 -c "import apt" >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  sudo apt-get install -y python-apt
fi

__aac2.py $*
